"""pdf_service.py — generate a prescription PDF with ReportLab.

Responsibility (Service): turn a prescription document into a nicely formatted PDF
file on local disk, and return its path. Storage/uploading is handled separately by
cloud_storage_service, keeping generation and storage as distinct concerns.
"""
from pathlib import Path

from flask import current_app
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

TEAL = colors.HexColor("#0f766e")
GREY = colors.HexColor("#6b7a90")
DARK = colors.HexColor("#1f2d3d")


def generate_prescription_pdf(prescription: dict) -> Path:
    """Render the prescription to a PDF file and return its local path."""
    output_dir = Path(current_app.config["GENERATED_PDF_DIR"])
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"prescription_{prescription['id']}.pdf"

    c = canvas.Canvas(str(path), pagesize=A4)
    width, height = A4
    left = 20 * mm
    y = height - 24 * mm

    # ---- Header band ----
    c.setFillColor(TEAL)
    c.rect(0, height - 18 * mm, width, 18 * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(left, height - 12 * mm, "MedCloud  ✚  Prescription")
    c.setFont("Helvetica", 9)
    c.drawRightString(width - left, height - 12 * mm, f"ID: {prescription['id']}")

    # ---- Patient / meta block ----
    y = height - 30 * mm
    c.setFillColor(DARK)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(left, y, "Patient")
    c.setFont("Helvetica", 10)
    c.setFillColor(GREY)
    c.drawString(left, y - 6 * mm, f"Name: {prescription.get('patient_name', '')}")
    c.drawString(left, y - 11 * mm, f"National ID: {prescription.get('patient_national_id', '')}")

    c.setFillColor(DARK)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(width / 2, y, "Prescriber")
    c.setFont("Helvetica", 10)
    c.setFillColor(GREY)
    c.drawString(width / 2, y - 6 * mm, f"Doctor: {prescription.get('doctor_name', '')}")
    created = prescription.get("created_at")
    created_str = created.strftime("%Y-%m-%d %H:%M") if hasattr(created, "strftime") else str(created or "")
    c.drawString(width / 2, y - 11 * mm, f"Date: {created_str}")

    # ---- Diagnosis ----
    y -= 22 * mm
    c.setFillColor(DARK)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(left, y, "Diagnosis")
    c.setFont("Helvetica", 10)
    c.setFillColor(GREY)
    c.drawString(left, y - 6 * mm, prescription.get("diagnosis") or "—")

    # ---- Items table ----
    y -= 16 * mm
    c.setFillColor(TEAL)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(left, y, "Medications")
    y -= 7 * mm
    c.setFillColor(colors.HexColor("#f7f9fc"))
    c.rect(left, y - 2 * mm, width - 2 * left, 8 * mm, fill=1, stroke=0)
    c.setFillColor(DARK)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(left + 2 * mm, y, "Drug")
    c.drawString(left + 70 * mm, y, "Dosage")
    c.drawString(left + 105 * mm, y, "Frequency")
    c.drawString(left + 140 * mm, y, "Duration")

    c.setFont("Helvetica", 9)
    c.setFillColor(GREY)
    y -= 9 * mm
    for item in prescription.get("items", []):
        if y < 40 * mm:  # simple page break
            c.showPage()
            y = height - 30 * mm
        c.drawString(left + 2 * mm, y, _clip(item.get("drug_name"), 42))
        c.drawString(left + 70 * mm, y, _clip(item.get("dosage"), 18))
        c.drawString(left + 105 * mm, y, _clip(item.get("frequency"), 18))
        c.drawString(left + 140 * mm, y, _clip(item.get("duration"), 18))
        if item.get("notes"):
            y -= 5 * mm
            c.setFont("Helvetica-Oblique", 8)
            c.drawString(left + 4 * mm, y, f"Note: {_clip(item.get('notes'), 90)}")
            c.setFont("Helvetica", 9)
        y -= 8 * mm

    # ---- Footer ----
    c.setStrokeColor(colors.HexColor("#dde5ef"))
    c.line(left, 26 * mm, width - left, 26 * mm)
    c.setFillColor(GREY)
    c.setFont("Helvetica", 8)
    c.drawString(left, 20 * mm, "Generated by MedCloud — Cloud Prescription Management.")
    c.drawString(left, 15 * mm, "This document is a demo prescription for an academic project.")

    c.showPage()
    c.save()
    return path


def _clip(text, length: int) -> str:
    text = str(text or "")
    return text if len(text) <= length else text[: length - 1] + "…"
